#basic input parameters
tile_size: 256
batch_size: 64
tiles_dir: tiles_11_13
num_channels: 31
n_clusters_celltypes: 27
n_clusters_preprocessing: 3
n_clusters_thresholding: 3
random_state: 2024

channel_names: ['DAPI', 'MPO', 'Ecadherin', 'PDL1', 'CD163', 'PD1', 'CD47', 'GAL3', 'PARP1', 'LAG3', 'CD4', 'PI3KCA', 'TIM3', 'CD68', 'ER', 'PR', 'MSH2', 'CD8', 'MSH6', 'bCatenin1', 'HLAABC', 'MLH1', 'Ki67', 'CD20', 'ARID1A', 'IFNG', 'CD31', 'PMS', 'CD44', 'PanCytokeratin', 'CD3e']

lineage_markers: ['DAPI', 'MPO', 'Ecadherin', 'CD163', 'CD4', 'CD68', 'CD8', 'CD20', 'CD31', 'CD3e'] 
threshold_channel_names: ['MPO', 'CD163', 'CD4', 'CD68', 'CD8', 'CD20', 'CD3e']
exclude_channel_names: ['pJAK1', 'CD56', 'MAL', 'Her2', 'STAT1']
samples_to_remove: null

#base paths
segmentation_data_dir: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/raw_segmentation_data
label_images_dir: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/label_images
out_dir: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/out_12-2-24

data_dir: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/out_256/data
qptiff_data_dir: /gpfs/data/proteomics/data/Endometrial_mIF/qptiff_dat

#specific paths: main_cell_segmentation
tiles_split_dir: tiles_split

#specific paths: main_cell_segmentation_analysis
thresholded_dir: thresholded_matrix
normalized_matrix_dir: normalized_matrix
metadata_filtered_path: normalized_matrix/metadata_filtered.csv
matrix_normal_filtered_path: normalized_matrix/matrix_normal_filtered_markers.npy
umap_dir: umap
umap_coord_path: umap/coord.npy
pca_coord_path: pca/coord.npy
clustering_dir: clustering
celltypes_dir: celltypes
omero_table_dir: omero_tables

#research drive
mount_lab: fenyolab
research_drive_dir: 'fenyolab/EC_codeximaging/cell_segmentation'

#omero image info
omero_image_dict:
  20230720-3660-2G-1_Scan1: 
    image_id: 597642
    roi_id: 1231686
    tile_roi_id: 1234393
  20230720-4309-4G-1_Scan1: 
    image_id: 597780
    roi_id: 1231684
    tile_roi_id: 1234391
  20230810_0488_3K_Scan1: 
    image_id: 601969 
    roi_id: 1231674
    tile_roi_id: 1234381
  20230908-1872-4C-1_Scan2: 
    image_id: 611987
    roi_id: 1231682
    tile_roi_id: 1234389
  20230908-6103-1J-1_Scan2: 
    image_id: 612242
    roi_id: 1231679
    tile_roi_id: 1234386
  20230908-8710-3H-1_Scan1: 
    image_id: 611002
    roi_id: 1231688
    tile_roi_id: 1234395
  20230922-3869-1O_Scan1: 
    image_id: 614300
    roi_id: 1231675
    tile_roi_id: 1234382
  20230922-5689-1P_Scan1: 
    image_id: 615142
    roi_id: 1231678
    tile_roi_id: 1234385
  20230922-7331-1H_Scan1: 
    image_id: 615004
    roi_id: 1231689
    tile_roi_id: 1234396
  20231003-1160-3S_Scan1: 
    image_id: 617515
    roi_id: 1231685
    tile_roi_id: 1234392
  20231003-2630-3P_Scan1: 
    image_id: 617353
    roi_id: 1231681
    tile_roi_id: 1234388
  20231003-5988-4I_Scan1: 
    image_id: 616589
    roi_id: 1231680
    tile_roi_id: 1234387
  20231012-3535-1T_Scan2: 
    image_id: 619802
    roi_id: 1231676
    tile_roi_id: 1234383
  20231012-9390-1I_Scan1: 
    image_id: 619234
    roi_id: 1231690
    tile_roi_id: 1234397
  20231012-9784-6H_Scan1: 
    image_id: 618713
    roi_id: 1231677
    tile_roi_id: 1234384
  20231019-0413-3D_Scan1: 
    image_id: 620931
    roi_id: 1231683
    tile_roi_id: 1234390
  20231019-4475-1E_Scan2: 
    image_id: 620498
    roi_id: 1231687
    tile_roi_id: 1234394

#lineage markers cluster identity  
lineage_markers_cluster_dict:
  20230720-3660-2G-1_Scan1:
    MPO: 
    CD163: 
      0: negative
      1: positive
      2: positive
    CD4: 
      0: negative
      1: positive
      2: negative
    CD68:
      lower_cutoff: 35 
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: negative
      2: negative
    CD3e:  
      0: negative
      1: positive
      2: positive
    DAPI: 8.5
    Ecadherin: 4
  20230720-4309-4G-1_Scan1: 
    MPO: 
    CD163: 
      lower_cutoff: 7
      upper_cutoff: 70
    CD4: 
      lower_cutoff: 18
    CD68: 
      lower_cutoff: 25
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: negative
      2: negative
    CD3e:  
      lower_cutoff: 16
    DAPI: 9
    Ecadherin: 4.75
  20230810_0488_3K_Scan1: 
    MPO: 
    CD163: 
      0: negative
      1: positive
      2: negative
    CD4: 
      0: negative
      1: negative
      2: positive
    CD68: 
      lower_cutoff: 18
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: negative
      2: negative
    CD3e: 
      0: negative
      1: positive
      2: positive 
    DAPI: 7.45
    Ecadherin: 4
  20230908-1872-4C-1_Scan2: 
    MPO: 
    CD163: 
      0: negative
      1: negative
      2: positive
    CD4: 
      0: negative
      1: negative
      2: positive
    CD68: 
      lower_cutoff: 35
    CD8:
      0: negative
      1: positive
      2: positive 
    CD20: 
      0: negative
      1: negative
      2: negative
    CD3e: 
      lower_cutoff: 7 
    DAPI: 8.5
    Ecadherin: 4
  20230908-6103-1J-1_Scan2: 
    MPO: 
    CD163: 
      lower_cutoff: 9
      upper_cutoff: 70
    CD4: 
      0: negative
      1: positive
      2: negative
    CD68: 
      lower_cutoff: 20
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: positive
      2: positive
    CD3e:  
      0: negative
      1: positive
      2: positive
    DAPI: 7.5
    Ecadherin: 5
  20230908-8710-3H-1_Scan1: 
    MPO: 
    CD163: 
      0: negative
      1: negative
      2: positive
    CD4: 
      0: negative
      1: positive
      2: negative
    CD68: 
      lower_cutoff: 45
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: positive
      2: negative
    CD3e:  
      lower_cutoff: 21
    DAPI: 7.5
    Ecadherin: 3
  20230922-3869-1O_Scan1: 
    MPO: 
    CD163: 
      lower_cutoff: 8
    CD4: 
      lower_cutoff: 20
    CD68: 
      lower_cutoff: 35
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: positive
      2: negative
    CD3e:  
      lower_cutoff: 17
    DAPI: 8.5
    Ecadherin: 3
  20230922-5689-1P_Scan1: 
    MPO: 
    CD163: 
      lower_cutoff: 13
    CD4: 
      0: negative
      1: positive
      2: negative
    CD68: 
      lower_cutoff: 30
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: positive
      2: negative
    CD3e:  
      0: negative
      1: positive
      2: positive
    DAPI: 8.5
    Ecadherin: 4
  20230922-7331-1H_Scan1: 
    MPO: 
    CD163: 
      lower_cutoff: 4
    CD4: 
      0: negative
      1: positive
      2: negative
    CD68: 
      lower_cutoff: 30
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: positive
      2: positive
    CD3e:  
      0: negative
      1: positive
      2: positive
    DAPI: 7.5
    Ecadherin: 6
  20231003-1160-3S_Scan1: 
    MPO: 
    CD163: 
      0: negative
      1: positive
      2: negative
    CD4: 
      0: negative
      1: positive
      2: negative
    CD68: 
      lower_cutoff: 30
    CD8: 
      0: positive
      1: negative
      2: positive
    CD20: 
      0: negative
      1: positive
      2: negative
    CD3e:  
      0: positive
      1: negative
      2: positive
    DAPI: 7.75
    Ecadherin: 4
  20231003-2630-3P_Scan1: 
    MPO: 
    CD163: 
      0: negative
      1: negative
      2: positive
    CD4: 
      lower_cutoff: 21
    CD68:
      lower_cutoff: 28 
    CD8: 
      lower_cutoff: 18
    CD20: 
      0: negative
      1: positive
      2: positive
    CD3e:  
      0: negative
      1: positive
      2: positive
    DAPI: 8.5
    Ecadherin: 6.5
  20231003-5988-4I_Scan1: 
    MPO: 
    CD163: 
      0: negative
      1: positive
      2: negative
    CD4: 
      lower_cutoff: 25
    CD68: 
      0: negative
      1: positive
      2: positive
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: positive
      2: negative
    CD3e:  
      lower_cutoff: 23
    DAPI: 7.75
    Ecadherin: 6
  20231012-3535-1T_Scan2: 
    MPO: 
    CD163: 
      0: negative
      1: negative
      2: positive
    CD4: 
      0: negative
      1: positive
      2: negative
    CD68: 
      0: negative
      1: negative
      2: positive
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: positive
      2: negative
    CD3e:  
      lower_cutoff: 16
    DAPI: 9
    Ecadherin: 2.5
  20231012-9390-1I_Scan1: 
    MPO: 
    CD163: 
      0: negative
      1: positive
      2: negative
    CD4: 
      0: negative
      1: negative
      2: positive
    CD68: 
      lower_cutoff: 27
    CD8: 
      lower_cutoff: 18
    CD20: 
      lower_cutoff: 12
    CD3e: 
      lower_cutoff: 38 
    DAPI: 11
    Ecadherin: 7
  20231012-9784-6H_Scan1: 
    MPO: 
    CD163: 
      0: negative
      1: negative
      2: positive
    CD4: 
      lower_cutoff: 22
    CD68: 
      0: negative
      1: positive
      2: positive
    CD8: 
      lower_cutoff: 15
    CD20: 
      0: negative
      1: positive
      2: negative
    CD3e: 
      lower_cutoff: 28
    DAPI: 7
    Ecadherin: 3
  20231019-0413-3D_Scan1: 
    MPO: 
    CD163: 
      lower_cutoff: 2
    CD4: 
      lower_cutoff: 9
    CD68: 
      0: negative
      1: positive
      2: positive
    CD8: 
      lower_cutoff: 7
    CD20: 
      lower_cutoff: 6
    CD3e:  
      0: negative
      1: positive
      2: positive
    DAPI: 7
    Ecadherin: 6
  20231019-4475-1E_Scan2: 
    MPO: 
    CD163: 
      lower_cutoff: 5
    CD4: 
      0: negative
      1: negative
      2: positive
    CD68: 
      lower_cutoff: 10
    CD8: 
      0: negative
      1: positive
      2: positive
    CD20: 
      0: negative
      1: negative
      2: negative
    CD3e: 
      0: negative
      1: positive
      2: positive 
    DAPI: 10
    Ecadherin: 3
