# REMINDER: add deepcell API key in bash_scripts/.env like below
# export DEEPCELL_ACCESS_TOKEN=<token-from-users.deepcell.org>
# Basic input parameters
tile_size: 256
batch_size: 64
tiles_dir: tiles_test
num_channels: 31
n_clusters_celltypes: 27
n_clusters_preprocessing: 3
n_clusters_thresholding: 3
random_state: 2024
membrane_marker: 'Ecadherin'
channel_names: ['DAPI', 'MPO', 'Ecadherin', 'PDL1', 'CD163', 'PD1', 'CD47', 'GAL3', 'PARP1', 'LAG3', 'CD4', 'PI3KCA', 'TIM3', 'CD68', 'ER', 'PR', 'MSH2', 'CD8', 'MSH6', 'bCatenin1', 'HLAABC', 'MLH1', 'Ki67', 'CD20', 'ARID1A', 'IFNG', 'CD31', 'PMS', 'CD44', 'PanCytokeratin', 'CD3e']

lineage_markers: ['DAPI', 'MPO', 'Ecadherin', 'CD163', 'CD4', 'CD68', 'CD8', 'CD20', 'CD31', 'CD3e'] 
threshold_channel_names: ['MPO', 'CD163', 'CD4', 'CD68', 'CD8', 'CD20', 'CD3e']
exclude_channel_names: ['pJAK1', 'CD56', 'MAL', 'Her2', 'STAT1']
samples_to_remove: null

# Base paths
segmentation_data_dir: /gpfs/data/proteomics/home/ca3261/sample_out/raw_segmentation_data
label_images_dir: /gpfs/data/proteomics/home/ca3261/sample_out/label_images
out_dir: /gpfs/data/proteomics/home/ca3261/sample_out/out_2-26-25

data_dir: /gpfs/data/proteomics/home/ca3261/sample_out/out_256/data
qptiff_data_dir: /gpfs/data/proteomics/home/ca3261/cervical_cancer/sample_imgs/Repository/59/fenyod01_956/2025-02/24/11-18-37.317

new_data_dir: /gpfs/data/proteomics/home/ca3261/sample_out/out_256/data_new
new_segmentation_data_dir: /gpfs/data/proteomics/home/ca3261/sample_out/raw_segmentation_data_new

# Specific paths: main_cell_segmentation
tiles_split_dir: tiles_split

# Specific paths: main_cell_segmentation_analysis
thresholded_dir: thresholded_matrix
normalized_matrix_dir: normalized_matrix
metadata_filtered_path: normalized_matrix/metadata_filtered.csv
matrix_normal_filtered_path: normalized_matrix/matrix_normal_filtered_markers.npy
umap_dir: umap
umap_coord_path: umap/coord.npy
pca_coord_path: pca/coord.npy
clustering_dir: clustering
celltypes_dir: celltypes
omero_table_dir: omero_tables

# Research drive
omero_dir: 'fenyolab/CC_codeximaging/cell_segmentation'
research_drive_dir: 'fenuolab-omero/CC_codeximaging/cell_segmentation'

# Omero image info # TODO - AUTOMATE
omero_image_dict:
  "20250318-Jharna-28873-A1_Scan1.er":
    image_id: 707635
  "20250318-Jharna-07291-1A_Scan1.er":
    image_id: 707494
  "20250318-Jharna-04738-A1_Scan1.er":
    image_id: 707353


# already processed
 # "20250305-Jharna-09002-A1_Scan1.er":
   # image_id: 701231
 # "20250225-Jharna-02433-A1_Scan1.er": 
   # image_id: 698744
 # "20250225-Jharna-07611-A3_Scan1.er":
   # image_id: 698885
 # "20250225-Jharna-08153-A1_Scan1.er":
   # image_id: 699026
 # "20250225-Jharna-10103-A1_Scan1.er":
   # image_id: 699167
 # "20250305-Jharna-34933-A1_Scan1.er":
   # image_id: 701509
 # "20250305-Jharna-00862-6X_Scan1.er":
   # image_id: 704253
 # "20250305-Jharna-10285-A21_Scan1.er":
   # image_id: 704478
 # "20250311-Jharna-00438-1A_Scan1.er":
   # image_id: 705910
 # "20250311-Jharna-07688-A1_Scan1.er":
   # image_id: 705491
 # "20250311-Jharna-39367-A1_Scan1.er":
   # image_id: 705632
 # "20250311-Jharna-49411-1A_Scan1.er":
   # image_id: 705769

# Lineage markers cluster identity - leave empty when doing first cell segmentation and fill out for analysis
lineage_markers_cluster_dict:
