
#these are the assigned cell types per cell: 20 clusters
celltypes: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/out_9-13-24b/clustering/20_clusters/phenotype_clusters.csv

#raw data
metadata_raw: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/raw_segmentation_data_old/metadata.csv
matrix_raw: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/raw_segmentation_data_old/matrix.npy
    
#Filtered and normalized data
metadata_filt: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/out_9-13-24b/normalized_matrix/metadata_filtered.csv
matrix_norm_filt: /gpfs/data/proteomics/projects/Endometrial_mIF/EC_codeximaging_results/out_9-13-24b/normalized_matrix/matrix_normal.npy

clinical_data: /gpfs/data/proteomics/data/Endometrial_mIF/canvas_files/dat/EC_Clinical_Data.csv

#cluster phenotypes 
cluster_celltype_labels:
  1: endothelial_cell 
  2: tumor_cell
  3: macrophage
  4: undefined 
  5: helper_Tcell
  6: cytotoxic_Tcell 
  7: undefined 
  8: tumor
  9: macrophage
  10: tumor_cell
  11: macrophage
  12: neutrophil 
  13: tumor_cell 
  14: cytotoxic_Tcell 
  15: immune_cell 
  16: neutrophil 
  17: Bcell 
  18: tumor 
  19: immune_cell
  20: undefined